// Shared English / Japanese editorial content. Keep claims tied to the sources below.
export const bi = (en, ja) => ({ en, ja });
export const site = { name: 'dot.wave', origin: 'https://dotwave.vercel.app', email: 'dotwave.creative@gmail.com', updated: '2026-09-18', featured: ['japan-wave-expo', 'si-juki', 'nila-baharuddin'] };
export const capabilities = [
 {id:'research',name:bi('Research & Strategy','リサーチ・戦略')},
 {id:'partnerships',name:bi('Partnerships & Market Access','パートナーシップ・市場開拓')},
 {id:'creative',name:bi('IP & Creative','IP・クリエイティブ')},
 {id:'live',name:bi('Live & Activation','イベント・アクティベーション')}
];
export const questions = [
 {title:bi('Entering Indonesia or Japan?','インドネシア、または日本での展開をお考えですか？'),text:bi('Market context, research and cultural understanding.','市場と生活者を理解し、文化や商習慣の違いを踏まえて方向性を整理します。'),outputs:bi('Market scans, audience insight, opportunity assessments and localization recommendations.','市場・競合調査、ターゲット分析、事業機会の整理、ローカライズの提案。')},
 {title:bi('Looking for the right partners?','適切なパートナーを探していますか？'),text:bi('Relevant companies, creators, institutions and communities.','企業、クリエイター、機関、コミュニティとの接点をつくります。'),outputs:bi('Partner landscapes, shortlists, introductions and facilitated business meetings.','パートナー候補の調査・選定、紹介、商談の調整・進行。')},
 {title:bi('Developing an idea or IP?','アイデアやIPを育てたいですか？'),text:bi('Positioning, storytelling and creative development.','現地の文脈に合うポジショニングとストーリーを形にします。'),outputs:bi('Brand and IP direction, creative concepts, content plans and activation ideas.','ブランド・IP戦略、クリエイティブコンセプト、コンテンツ計画、施策の企画。')},
 {title:bi('Ready to make it happen?','実行を支えるチームが必要ですか？'),text:bi('Planning, production and on-the-ground coordination.','計画から制作、現場の調整まで、実現に向けて伴走します。'),outputs:bi('Delivery plans, production, vendor coordination, exhibitions, events and launch programs.','実施計画、制作、協力会社の調整、展示会・イベント・ローンチの運営。')}
];
export const services = [
 bi('Research & Insight','リサーチ・インサイト'),bi('Strategy & Advisory','戦略・アドバイザリー'),bi('Partnerships & Connections','パートナーシップ・ネットワーク'),bi('Creative & IP Development','クリエイティブ・IP開発'),bi('Execution & Delivery','制作・実行支援')
];
export const engagements = [
 [bi('Focused research sprint','テーマを絞ったリサーチ'),bi('A defined business question, a clear evidence base and useful recommendations.','一つの経営・事業課題に対し、判断に必要な情報と提案をまとめます。')],
 [bi('Strategy or advisory','戦略・アドバイザリー'),bi('Local context and an outside perspective before your next decision.','現地の文脈と客観的な視点から、次の意思決定を支援します。')],
 [bi('Partner search & introductions','パートナー探索・紹介'),bi('Find the companies, creators or institutions that fit the opportunity.','目的に合う企業、クリエイター、機関との接点をつくります。')],
 [bi('Creative or activation development','企画・アクティベーション開発'),bi('Develop an early idea into a relevant concept, campaign or experience.','初期のアイデアを、現地で伝わる企画や体験へと具体化します。')],
 [bi('End-to-end delivery','戦略から実施まで'),bi('Connect strategy, partners, production and execution in one project.','戦略、パートナー、制作、運営を一つのプロジェクトとして進めます。')],
 [bi('Ongoing advisory','継続的なアドバイザリー'),bi('Continued market insight, connections and decision support as needs evolve.','状況の変化に合わせ、市場理解、ネットワーク、意思決定を継続して支援します。')]
];
export const process = [
 {name:bi('Understand','理解する'),short:bi('Frame the question. Ground it in evidence.','課題を整理し、根拠を集める。'),detail:bi('We agree on the objective, audience and constraints, then research the market and cultural context. The output is a shared brief and a practical view of the opportunity.','目的、対象、条件を確認し、市場や文化的背景を調査します。共通のブリーフをつくり、機会と課題を整理します。')},
 {name:bi('Connect','つなぐ'),short:bi('Bring the right people into the picture.','必要な人と関係をつくる。'),detail:bi('We map relevant partners, stakeholders and specialist expertise. Your project lead coordinates introductions and responsibilities so the working team is clear.','関連する企業や関係者、専門家を見極めます。プロジェクトリードが紹介と役割分担を調整し、実行体制を明確にします。')},
 {name:bi('Create','形にする'),short:bi('Turn insight into a workable direction.','洞察を、実行できる方向性へ。'),detail:bi('We develop the strategy, concept or program with the people who will use it. Ideas are tested against local context, resources and the agreed objective.','戦略、コンセプト、プログラムを具体化します。現地の文脈、リソース、合意した目的に照らし、実現性を確認します。')},
 {name:bi('Deliver','届ける'),short:bi('Put the agreed work into practice.','合意した内容を実行する。'),detail:bi('Delivery may mean recommendations, introductions, content, a launch or an on-the-ground program. We coordinate the agreed scope and review what the work achieved.','提案書、紹介、コンテンツ、ローンチ、現地プログラムなど、合意した成果物を届けます。進行を管理し、実施結果を振り返ります。')}
];
export const members = [
 {id:'faza',name:'Faza Meonk',alias:'faza.wave',cofounder:true,image:'faza.jpg',territory:bi('IP & Creative Development','IP・クリエイティブ開発'),proof:bi('Creator of Si Juki, an Indonesian character IP spanning comics, animation and brand collaborations.','コミック、アニメーション、ブランド協業へと広がるインドネシア発IP「Si Juki」の生みの親。'),expertise:bi('Character IP · Storytelling · Licensing · Creative worlds','キャラクターIP・ストーリー・ライセンス・世界観構築'),bio:bi('Faza created Si Juki under PIONICON IP Management. His work shows how a character can develop into a wider creative and commercial ecosystem across publishing, animation, games and collaborations.','PIONICON IP ManagementのもとでSi Jukiを生み出し、出版、アニメーション、ゲーム、協業へと展開。キャラクターの魅力を、多様な表現と事業につなげてきました。'),highlights:[bi('65+ printed comic titles reported by Si Juki.','Si Juki公式サイト掲載：コミック65タイトル以上。'),bi('100+ brand collaborations across the IP ecosystem.','IP全体で100ブランド以上との協業。')],url:'https://www.sijuki.com/'},
 {id:'rini',name:'Rinintha Pradiza',alias:'rini.wave',cofounder:true,image:'rini.jpg',territory:bi('Strategy & Cross-Market Projects','戦略・クロスマーケット事業'),proof:bi('15+ years connecting strategy, brands and complex projects across Indonesia and Japan.','15年以上にわたり、インドネシアと日本の戦略、ブランド、多様なプロジェクトをつなぐ。'),expertise:bi('Strategy · Research · Partnerships · Project leadership','戦略・リサーチ・パートナーシップ・プロジェクト推進'),bio:bi('Rinintha combines market understanding, creative direction and delivery. Her experience spans Japanese Station, JETRO-initiated Japan Wave Expo, K-Content Expo Indonesia, fashion market development and original live properties.','市場理解、クリエイティブの方向づけ、実行を横断。Japanese Station、JETRO主導のJapan Wave Expo、K-Content Expo Indonesia、ファッションの市場開拓、独自イベントの開発などを経験しています。'),highlights:[bi('Creative & Delivery Lead for Japan Wave Expo, connecting 16 Japanese companies with Indonesia.','Japan Wave Expoで企画・実行をリード。日本企業16社とインドネシアをつなぐ。'),bi('Created Hyper Wave Festival, with 5,000+ attendees.','5,000人以上が来場したHyper Wave Festivalを企画。'),bi('Led Nila Baharuddin’s Japan market development.','Nila Baharuddinの日本市場開拓を担当。')],url:'https://www.rinintha.com/'},
 {id:'andhika',name:'Andhika Putra',alias:'andhika.wave',image:'andhika-new.jpg',territory:bi('Investment & Japan Relations','投資・日本とのビジネス連携'),proof:bi('Experience in Indonesia–Japan investment promotion, investor consultation and business matching.','日・インドネシア間の投資促進、投資家対応、ビジネスマッチングを経験。'),expertise:bi('Investment · Business matching · Research · Japan relations','投資・ビジネスマッチング・リサーチ・日本連携'),bio:bi('Andhika brings a Japan-based perspective to cross-border business. His background connects investment research, corporate and government stakeholders, and cultural localization.','日本を拠点とする視点から、国境を越えるビジネスを支援。投資調査、企業・行政との調整、文化的なローカライズをつなぐ経験を持ちます。'),highlights:[bi('Selected experience: investment promotion and business matching through IIPC Tokyo.','主な経験：IIPC Tokyoでの投資促進・ビジネスマッチング。')],url:'https://www.linkedin.com/in/andhika-putra-61394434/'},
 {id:'arno',name:'Arno Prawidhana',alias:'arno.wave',image:'arno.jpg',territory:bi('Research, Innovation & Activation','リサーチ・イノベーション・施策企画'),proof:bi('Experience connecting innovation consulting, brand development and consumer-facing activation.','イノベーション支援、ブランド開発、生活者向け施策を横断する経験。'),expertise:bi('Research · Innovation · Brand development · Activation','リサーチ・イノベーション・ブランド開発・アクティベーション'),bio:bi('Arno connects research and ideas with the realities of brand delivery. His experience includes innovation consulting, campaign development and activation across consumer, technology, lifestyle and hospitality contexts.','リサーチとアイデアを、ブランドの実行につなげます。消費財、テクノロジー、ライフスタイル、ホスピタリティの領域で、イノベーション支援やキャンペーン開発、施策を経験しています。'),highlights:[bi('Selected experience: Innovesia, Cheil Worldwide and brand activation.','主な経験：Innovesia、Cheil Worldwide、ブランドアクティベーション。')],url:'https://www.linkedin.com/in/arno'},
 {id:'resky',name:'Resky Ramadhan',alias:'resky.wave',image:'resky.jpg',territory:bi('Visual Storytelling & Production','ビジュアルストーリー・制作'),proof:bi('Photographer and creative producer working across fashion, music and brands between Jakarta and Tokyo.','ジャカルタと東京をつなぎ、ファッション、音楽、ブランドを撮るフォトグラファー／クリエイティブプロデューサー。'),expertise:bi('Photography · Production · Content · Social media','写真・制作・コンテンツ・ソーシャルメディア'),bio:bi('Working as THE 1993, Resky brings a visual and production perspective to the collective. His portfolio includes campaign, fashion and music imagery, including Erigo’s Japan campaign and work around JKT48.','THE 1993として、写真と制作の視点をコレクティブに加えます。Erigoの日本キャンペーンやJKT48関連の撮影など、広告、ファッション、音楽の作品を手がけています。'),highlights:[bi('Travel with Erigo Japan Campaign.','Travel with Erigo日本キャンペーン。'),bi('Fashion, editorial and music imagery through THE 1993.','THE 1993でのファッション、エディトリアル、音楽の撮影。')],url:'https://the1993.co/'}
];
const riniSource = 'https://www.rinintha.com/work';
export const projects = [
 {id:'japan-wave-expo',title:'Japan Wave Expo',year:'2016',member:'rini',categories:['partnerships','live'],client:'JETRO-initiated program',market:bi('Japan → Indonesia · Jakarta','日本 → インドネシア・ジャカルタ'),image:'japan-wave.jpg',alt:bi('Fashion showcase at Japan Wave Expo in Jakarta.','ジャカルタで開催されたJapan Wave Expoのファッションショー。'),credit:'Rinintha Pradiza portfolio',source:riniSource+'#japan-wave',summary:bi('Japanese fashion meets Indonesian buyers, media and audiences.','日本のファッションと、インドネシアのバイヤー・メディア・生活者をつなぐ。'),scope:bi('A three-day platform combining business matching, test marketing, fashion showcases and public programming for 16 Japanese companies.','日本企業16社が参加した3日間のプログラム。商談、テストマーケティング、ファッションショー、一般向け企画を組み合わせました。'),challenge:bi('Make a fashion-business mission relevant to buyers and consumers in Jakarta, while connecting commercial objectives with a public experience.','ファッションの商談機会をジャカルタのバイヤーと生活者に伝え、ビジネスと一般向け体験を結びつけること。'),contribution:bi('Rinintha served as Creative & Delivery Lead: concepts, proposals, client and sponsor relationships, budgets, programming, fashion-show direction, international coordination and venue delivery.','Rininthaが企画・実行責任者として、コンセプト、提案、クライアント・スポンサー対応、予算、プログラム、ショー演出、国際調整、会場運営を担当しました。'),outcome:bi('The program connected 16 Japanese companies with Indonesian buyers, media and consumers across Central Park and Tribeca Park.','Central ParkとTribeca Parkで、日本企業16社をインドネシアのバイヤー、メディア、生活者につなぎました。'),metric:'16',metricLabel:bi('Japanese companies','日本企業が参加')},
 {id:'si-juki',title:'Si Juki',year:bi('2010 onward','2010年〜'),member:'faza',categories:['creative','partnerships'],client:'PIONICON IP Management',market:bi('Indonesia · International collaborations','インドネシア・国際的な協業'),image:'si-juki.jpg',alt:bi('Si Juki comic characters and illustrated world.','Si Jukiのキャラクターとコミックの世界。'),credit:'Si Juki / PIONICON · Created by Faza Meonk',source:'https://www.sijuki.com/',summary:bi('A character that grew into a publishing, animation and collaboration ecosystem.','一つのキャラクターから、出版、アニメーション、協業へ。'),scope:bi('An Indonesian character IP spanning comics, animation, games, licensed products and brand collaborations, developed under PIONICON.','PIONICONのもとで、コミック、アニメーション、ゲーム、ライセンス商品、ブランド協業に展開するインドネシアのキャラクターIP。'),challenge:bi('Extend a distinctive character and storytelling world across formats while maintaining a recognizable identity.','キャラクターらしさを保ちながら、多様なメディアや商品へと表現を広げること。'),contribution:bi('Faza Meonk is the creator of Si Juki. The wider publishing, animation and commercial outcomes reflect the work of PIONICON and its collaborators.','Faza MeonkはSi Jukiの生みの親です。出版、映像、事業面の成果は、PIONICONと多くの協業先によるものです。'),outcome:bi('Si Juki’s official site reports 65+ printed comic titles and more than 100 brand collaborations. The IP also spans animation and games.','公式サイトでは、コミック65タイトル以上、100ブランド以上との協業を紹介。アニメーションやゲームにも展開しています。'),metric:'65+',metricLabel:bi('printed comic titles','コミックタイトル')},
 {id:'nila-baharuddin',title:'Nila Baharuddin',year:'2023–2025',member:'rini',categories:['research','partnerships','creative'],client:'Nila Baharuddin',market:bi('Indonesia → Japan · Tokyo','インドネシア → 日本・東京'),image:'nila.jpg',alt:bi('Nila Baharuddin fashion design featured in Rinintha’s portfolio.','Rininthaのポートフォリオに掲載されたNila Baharuddinのファッション作品。'),credit:'Rinintha Pradiza portfolio / Nila Baharuddin',source:riniSource+'#nila-baharuddin',summary:bi('Building an Indonesian fashion label’s presence in Japan.','インドネシアのファッションブランドの日本展開。'),scope:bi('Japan market development across FEELSEEN Ginza, NEW ENERGY Tokyo and Daimaru Tokyo, connecting brand strategy, cultural storytelling and retail.','FEELSEEN銀座、NEW ENERGY Tokyo、大丸東京での市場開拓。ブランド戦略、文化的なストーリー、販売をつなぐ取り組み。'),challenge:bi('Translate an Indonesian designer’s proposition into credible gallery, trade-fair and department-store experiences in Japan.','インドネシアのデザイナーの価値を、日本のギャラリー、展示会、百貨店で伝わる形にすること。'),contribution:bi('As Brand Marketing Manager, Rinintha led strategy, storytelling, production coordination, pricing, inventory, shipping, PR and retail support. Following an introduction by a Japan-based consultant, she managed the Daimaru buyer relationship and helped develop the pop-up.','ブランドマーケティングマネージャーとして、戦略、ストーリー、制作調整、価格、在庫、輸送、PR、販売支援を担当。日本のコンサルタントによる紹介後、大丸のバイヤー対応とポップアップ開発を進めました。'),outcome:bi('The program progressed from Ginza to a Tokyo trade fair and department-store retail. The two-week Daimaru pop-up surpassed ¥1 million in retail sales, a project result supported by the wider team.','銀座から東京の展示会、百貨店へと展開。2週間の大丸ポップアップでは売上100万円超を達成しました。これはチーム全体による事業成果です。'),metric:'¥1M+',metricLabel:bi('Daimaru pop-up retail sales','大丸ポップアップ売上')},
 {id:'k-content-expo',title:'K-Content Expo Indonesia',year:'2016',member:'rini',categories:['partnerships','live'],client:'KOCCA–BEKRAF cultural showcase',market:bi('Korea → Indonesia · ICE BSD','韓国 → インドネシア・ICE BSD'),image:'kcontent.jpg',alt:bi('Panoramic view of K-Content Expo Indonesia at ICE BSD.','ICE BSDで開催されたK-Content Expo Indonesiaの会場全景。'),credit:'Rinintha Pradiza portfolio',source:riniSource+'#k-content',summary:bi('Coordinating a complex international content showcase.','国際的なコンテンツ展示会の複雑な現場をまとめる。'),scope:bi('A public cultural showcase spanning gaming, music, beauty, food, screenings and official networking.','ゲーム、音楽、ビューティー、食、上映、公式ネットワーキングを含む文化プログラム。'),challenge:bi('Connect technical, talent, government and vendor requirements in one coherent public program.','技術、出演者、行政、協力会社それぞれの要件を、一貫したプログラムとして実現すること。'),contribution:bi('As Head of Project and Show Director, Rinintha led 19 local staff and freelancers across programming, rehearsals, stage management, technical delivery, vendors and stakeholder coordination.','Head of Project／Show Directorとして、現地スタッフとフリーランス計19人を統括。企画、リハーサル、舞台、技術、協力会社、関係者調整を担当しました。'),outcome:bi('The planned public-stage programs and official networking were delivered, demonstrating coordination across a wide range of stakeholders and content formats.','予定されたステージプログラムと公式ネットワーキングを実施。多様な関係者とコンテンツを調整した経験です。'),metric:'19',metricLabel:bi('local staff & freelancers led','現地チームを統括')},
 {id:'hyper-wave-festival',title:'Hyper Wave Festival',year:'2013',member:'rini',categories:['creative','live'],client:'Japanese Station / Hyper Wave Festival',market:bi('Indonesia ↔ Japan · Jakarta','インドネシア ↔ 日本・ジャカルタ'),image:'hyper-wave.jpg',alt:bi('VAMPS performing at Hyper Wave Festival in Jakarta.','ジャカルタのHyper Wave Festivalで演奏するVAMPS。'),credit:'Rinintha Pradiza portfolio',source:riniSource+'#japanese-station-hyper-wave',summary:bi('An original live property connecting Japanese and Indonesian music audiences.','日本とインドネシアの音楽ファンをつなぐ独自イベント。'),scope:bi('A two-day cross-cultural music festival with three Japanese artists and five Indonesian bands.','日本のアーティスト3組、インドネシアのバンド5組が参加した2日間の音楽フェスティバル。'),challenge:bi('Build an original festival with a credible audience proposition, sponsor story and international artist program.','来場者への魅力、スポンサーへの価値、海外アーティストのプログラムを備えた独自フェスを立ち上げること。'),contribution:bi('Rinintha created the festival concept and led creative direction, sponsorship narrative, artist liaison, venue coordination, executive production and show delivery.','Rininthaがコンセプトを開発し、クリエイティブ、スポンサー提案、アーティスト対応、会場調整、総合制作、ショー運営をリードしました。'),outcome:bi('The festival brought 5,000+ attendees together across two days, with a line-up including VAMPS and NIDJI.','VAMPS、NIDJIなどが出演し、2日間で5,000人以上が来場しました。'),metric:'5,000+',metricLabel:bi('festival attendees','フェスティバル来場者')},
 {id:'project-ia',title:'Project IA',year:'2019',member:'rini',categories:['research'],client:bi('Client name not published','クライアント名非公開'),market:bi('Market & audience research','市場・オーディエンス調査'),source:riniSource,summary:bi('Research and advisory built around a practical decision.','意思決定に向けたリサーチとアドバイザリー。'),scope:bi('A research and advisory engagement covering market landscaping, social listening, audience profiling, event comparison and case-study analysis.','市場調査、ソーシャルリスニング、オーディエンス分析、イベント比較、事例分析を含むリサーチ・アドバイザリー業務。'),challenge:bi('Bring different evidence sources together into a usable basis for strategic recommendations.','複数の情報源を整理し、戦略的な提案の根拠をつくること。'),contribution:bi('Rinintha delivered the research and advisory engagement documented in her portfolio, including market and audience analysis and practical recommendations.','ポートフォリオに記載された市場・オーディエンス分析と実践的な提案を含むリサーチ・アドバイザリー業務を担当しました。'),outcome:bi('The engagement produced practical strategic recommendations. The public record does not disclose commercial results or client identity.','実践的な戦略提案をまとめました。クライアント名と事業上の成果は公開されていません。')}
];
export const faq = [
 [bi('Can we begin with research only?','リサーチだけでも依頼できますか？'),bi('Yes. A focused research or advisory assignment can be a complete engagement. Scope can grow if the project calls for it.','はい。テーマを絞ったリサーチやアドバイザリーのみでも対応します。必要に応じて、その後の戦略や実行へ広げることもできます。')],
 [bi('Can you work with our existing team?','既存の社内チームや代理店と協働できますか？'),bi('Yes. We can work alongside your internal team, agency or local partner, with responsibilities agreed before the project begins.','はい。社内チーム、代理店、現地パートナーと協働できます。開始前に役割と責任範囲を明確にします。')],
 [bi('How are projects scoped and contracted?','契約や請求はどのように行いますか？'),bi('Each engagement starts with a proposal covering scope, team, timeline and fees. Formal contracting and invoicing are handled through an Indonesian legal entity, identified in the proposal.','業務範囲、体制、スケジュール、費用を提案書で確認します。契約・請求はインドネシアの法人を通じて行い、法人名は提案時にお伝えします。')],
 [bi('Can you sign an NDA?','秘密保持契約（NDA）に対応できますか？'),bi('Yes. Let us know before sharing confidential material so the appropriate agreement can be put in place.','はい。機密資料をお送りいただく前にご相談ください。必要な契約を整えたうえで進めます。')],
 [bi('Do you support strategy and execution?','戦略と実行の両方に対応していますか？'),bi('Yes. Engage us for strategy, execution, or the full journey between them. We recommend the smallest useful scope.','はい。戦略、実行、またはその両方に対応します。目的に対して必要な範囲をご提案します。')],
 [bi('Which languages can we work in?','対応言語を教えてください。'),bi('Tell us your language requirements. We assemble the appropriate Indonesian, English and Japanese support around the project and confirm it in the scope.','インドネシア語、英語、日本語について、ご希望をお知らせください。必要な言語対応を体制に組み込み、業務範囲で確認します。')],
 [bi('Do you offer ongoing support?','継続的な支援は可能ですか？'),bi('Yes. Work can be structured as a defined project or ongoing advisory, depending on the need. We do not publish fixed packages or fees.','はい。個別プロジェクトでも継続的なアドバイザリーでも対応します。固定のパッケージや料金表ではなく、内容に応じてご提案します。')]
];
